[build]
  publish = "dist"
  command = "npm run build && node scripts/build-functions.js"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "drizzle-orm", "@neondatabase/serverless"]

[dev]
  command = "npm run dev"
  port = 5000